framework:
  messenger:
    transports:
      async: "%env(MESSENGER_TRANSPORT_DSN)%"

    routing:
      # async is whatever name you gave your transport above
      'App\Message\RecapMessage':  async
      'App\Message\EducatorImportMessage':  async
      'App\Message\StudentImportMessage':  async